Repository SeSACTHON-Winner/SeSACTHON-Front, pull requests merged in 2023-06, with the labels that each got.

#10 [Design/#9] 디자인 없는 기본 ContentView & Run Map View 생성
  SeSACTHON_App/SeSACTHON_App.xcodeproj/project.pbxproj
  SeSACTHON_App/SeSACTHON_App/View/ContentView.swift
  SeSACTHON_App/SeSACTHON_App/View/MainMapView.swift
  SeSACTHON_App/SeSACTHON_App/View/MainRunView.swift
Labels: Design

#14 [Feat/#13] Background location update 활성화
  SeSACTHON_App/SeSACTHON-App-Info.plist
  SeSACTHON_App/SeSACTHON_App.xcodeproj/project.pbxproj
  SeSACTHON_App/SeSACTHON_App/Global/Components/CustomMapView.swift
  SeSACTHON_App/SeSACTHON_App/Global/LocationDataManager.swift
  SeSACTHON_App/SeSACTHON_App/Model/CurrentLocationMO.swift
Labels: feat

#16 [Design/#15] LaunchScreen 추가
  SeSACTHON_App/SeSACTHON-App-Info.plist
  SeSACTHON_App/SeSACTHON_App.xcodeproj/project.pbxproj
  SeSACTHON_App/SeSACTHON_App/Resources/Assets.xcassets/LoadingImg.imageset/Contents.json
  SeSACTHON_App/SeSACTHON_App/Resources/Assets.xcassets/LoadingImg.imageset/LoadingImg.png
  SeSACTHON_App/SeSACTHON_App/Resources/Assets.xcassets/LoadingImg.imageset/LoadingImg@2x.png
  SeSACTHON_App/SeSACTHON_App/Resources/Assets.xcassets/LoadingImg.imageset/LoadingImg@3x.png
Labels: Design

#18 [Design/#17] ContentView 디자인 수정
  SeSACTHON_App/SeSACTHON_App/Resources/Assets.xcassets/MainGoLeft.imageset/Contents.json
  SeSACTHON_App/SeSACTHON_App/Resources/Assets.xcassets/MainGoLeft.imageset/MainGoLeft.png
  SeSACTHON_App/SeSACTHON_App/Resources/Assets.xcassets/MainGoLeft.imageset/MainGoLeft@2x.png
  SeSACTHON_App/SeSACTHON_App/Resources/Assets.xcassets/MainGoLeft.imageset/MainGoLeft@3x.png
  SeSACTHON_App/SeSACTHON_App/Resources/Assets.xcassets/MainGoRight.imageset/Contents.json
  SeSACTHON_App/SeSACTHON_App/Resources/Assets.xcassets/MainGoRight.imageset/MainGoRight.png
  SeSACTHON_App/SeSACTHON_App/Resources/Assets.xcassets/MainGoRight.imageset/MainGoRight@2x.png
  SeSACTHON_App/SeSACTHON_App/Resources/Assets.xcassets/MainGoRight.imageset/MainGoRight@3x.png
  SeSACTHON_App/SeSACTHON_App/View/ContentView.swift
Labels: Design

#21 [Feat/#20] MapSearchView 자동완성 추가 -> 위도 경도를 로그로 반환
  SeSACTHON_App/SeSACTHON_App/Global/Components/MapSearchView.swift
  SeSACTHON_App/SeSACTHON_App/View/MainMapView.swift
Labels: feat

#23 [Feat/#22] Map 현재위치 버튼 기능 추가
  SeSACTHON_App/SeSACTHON_App/Global/Components/CustomMapView.swift
  SeSACTHON_App/SeSACTHON_App/Global/Components/MapSearchView.swift
  SeSACTHON_App/SeSACTHON_App/View/MainMapView.swift
Labels: feat

#25 [Design/#24] ContentView 디자인 변경사항 반영
  SeSACTHON_App/SeSACTHON_App/Resources/Assets.xcassets/DoubleChebronDownGray.imageset/Contents.json
  SeSACTHON_App/SeSACTHON_App/Resources/Assets.xcassets/DoubleChebronDownGray.imageset/DoubleChebronDownGray.png
  SeSACTHON_App/SeSACTHON_App/Resources/Assets.xcassets/DoubleChebronDownGray.imageset/DoubleChebronDownGray@2x.png
  SeSACTHON_App/SeSACTHON_App/Resources/Assets.xcassets/DoubleChebronDownGray.imageset/DoubleChebronDownGray@3x.png
  SeSACTHON_App/SeSACTHON_App/Resources/Assets.xcassets/DoubleChebronDownWhite.imageset/Contents.json
  SeSACTHON_App/SeSACTHON_App/Resources/Assets.xcassets/DoubleChebronDownWhite.imageset/DoubleChebronDownWhite.png
  SeSACTHON_App/SeSACTHON_App/Resources/Assets.xcassets/DoubleChebronDownWhite.imageset/DoubleChebronDownWhite@2x.png
  SeSACTHON_App/SeSACTHON_App/Resources/Assets.xcassets/DoubleChebronDownWhite.imageset/DoubleChebronDownWhite@3x.png
  SeSACTHON_App/SeSACTHON_App/View/ContentView.swift
Labels: Design

#27 [Feat/#26] 위도 경도로 주소 구하기
  SeSACTHON_App/SeSACTHON_App.xcodeproj/project.pbxproj
  SeSACTHON_App/SeSACTHON_App/Global/Components/CustomMapView.swift
  SeSACTHON_App/SeSACTHON_App/Global/Components/MapSearchView.swift
  SeSACTHON_App/SeSACTHON_App/Global/LocationDataManager.swift
  SeSACTHON_App/SeSACTHON_App/Model/CurrentLocationMO.swift
  SeSACTHON_App/SeSACTHON_App/View/MainMapView.swift
Labels: feat

#29 [Design/#28] SFPro 폰트 추가, 폰트 디자인 적용
  SeSACTHON_App/SeSACTHON_App.xcodeproj/project.pbxproj
  SeSACTHON_App/SeSACTHON_App/Global/Components/MapRouteInfoView.swift
  SeSACTHON_App/SeSACTHON_App/Global/Modifier/BlueSystemImageLabelStyle.swift
  SeSACTHON_App/SeSACTHON_App/Resources/Font/Pilseung Gothic Regular.otf
  SeSACTHON_App/SeSACTHON_App/Resources/Font/SF-Pro-Text-BlackItalic.otf
  SeSACTHON_App/SeSACTHON_App/SeSACTHON_AppApp.swift
  SeSACTHON_App/SeSACTHON_App/View/ContentView.swift
Labels: Design

#32 [Design/#31] MapSearchView & MapRouteInfoView 디자인 수정
  SeSACTHON_App/SeSACTHON_App.xcodeproj/project.pbxproj
  SeSACTHON_App/SeSACTHON_App/Global/Components/MapRouteInfoView.swift
  SeSACTHON_App/SeSACTHON_App/Global/Components/MapSearchView.swift
  SeSACTHON_App/SeSACTHON_App/Global/Components/RoundedCorner.swift
  SeSACTHON_App/SeSACTHON_App/Global/Extension/ViewExtension.swift
  SeSACTHON_App/SeSACTHON_App/View/MainMapView.swift
Labels: Design

#34 [Feat/#33] 네비게이션 기능 완성 (장애물 개수 확인 기능 제외)
  SeSACTHON_App/SeSACTHON_App.xcodeproj/project.pbxproj
  SeSACTHON_App/SeSACTHON_App/Global/Components/MapRouteInfoView.swift
  SeSACTHON_App/SeSACTHON_App/Global/Components/MapSearchView.swift
  SeSACTHON_App/SeSACTHON_App/Global/Components/NavigationMapView.swift
  SeSACTHON_App/SeSACTHON_App/Global/LocationDataManager.swift
  SeSACTHON_App/SeSACTHON_App/Global/Modifier/modifierExample.swift
  SeSACTHON_App/SeSACTHON_App/Model/CurrentLocationMO.swift
  SeSACTHON_App/SeSACTHON_App/Model/modelExample.swift
  SeSACTHON_App/SeSACTHON_App/View/MainMapView.swift
Labels: feat

#37 Radin feat/#30
  SeSACTHON_App/SeSACTHON-App-Info.plist
  SeSACTHON_App/SeSACTHON_App.xcodeproj/project.pbxproj
  SeSACTHON_App/SeSACTHON_App/Global/Components/CustomCameraView.swift
  SeSACTHON_App/SeSACTHON_App/Model/CameraModel.swift
  SeSACTHON_App/SeSACTHON_App/Model/CameraViewModel.swift
  SeSACTHON_App/SeSACTHON_App/Resources/Assets.xcassets/Camera.imageset/Contents.json
  SeSACTHON_App/SeSACTHON_App/Resources/Assets.xcassets/Camera.imageset/Property 1=Variant3Camera.png
  SeSACTHON_App/SeSACTHON_App/Resources/Assets.xcassets/Camera.imageset/Property@2x.png
  SeSACTHON_App/SeSACTHON_App/Resources/Assets.xcassets/Camera.imageset/Property@3x.png
  SeSACTHON_App/SeSACTHON_App/View/MainRunView.swift
  SeSACTHON_App/SeSACTHON_App/View/ReportSubmitView.swift
Labels: feat

#41 Radin design/#40
  SeSACTHON_App/SeSACTHON_App.xcodeproj/project.pbxproj
  SeSACTHON_App/SeSACTHON_App/Resources/Assets.xcassets/Colors/Contents.json
  SeSACTHON_App/SeSACTHON_App/Resources/Assets.xcassets/Colors/ListBackgroundColor.colorset/Contents.json
  SeSACTHON_App/SeSACTHON_App/Resources/Assets.xcassets/Colors/MainColor.colorset/Contents.json
  SeSACTHON_App/SeSACTHON_App/View/MainRunView.swift
  SeSACTHON_App/SeSACTHON_App/View/RunEndView.swift
Labels: Design

#43 [Feat/#42] Watch App 추가
  SeSACTHON_App/SeSACTHON_App.xcodeproj/project.pbxproj
  SeSACTHON_App/SeSACTHON_Watch Watch App/Assets.xcassets/AccentColor.colorset/Contents.json
  SeSACTHON_App/SeSACTHON_Watch Watch App/Assets.xcassets/AppIcon.appiconset/Contents.json
  SeSACTHON_App/SeSACTHON_Watch Watch App/Assets.xcassets/Contents.json
  SeSACTHON_App/SeSACTHON_Watch Watch App/ContentView.swift
  SeSACTHON_App/SeSACTHON_Watch Watch App/Preview Content/Preview Assets.xcassets/Contents.json
  SeSACTHON_App/SeSACTHON_Watch Watch App/SeSACTHON_WatchApp.swift
Labels: feat

#45 [Feat/#44] 네비게이션 기능 삭제
  SeSACTHON_App/SeSACTHON_App.xcodeproj/project.pbxproj
  SeSACTHON_App/SeSACTHON_App/Global/Components/CustomMapView.swift
  SeSACTHON_App/SeSACTHON_App/Global/Components/MapRouteInfoView.swift
  SeSACTHON_App/SeSACTHON_App/Global/Components/MapSearchView.swift
  SeSACTHON_App/SeSACTHON_App/Global/Components/NavigationMapView.swift
  SeSACTHON_App/SeSACTHON_App/Global/Components/PlaceAnnotationView.swift
  SeSACTHON_App/SeSACTHON_App/Global/Components/TopProfileView.swift
  SeSACTHON_App/SeSACTHON_App/Global/Components/componentExample.swift
  SeSACTHON_App/SeSACTHON_App/Global/Modifier/MintSystemImageLabelStyle.swift
  SeSACTHON_App/SeSACTHON_App/Model/PlaceMO.swift
  SeSACTHON_App/SeSACTHON_App/View/MainMapView.swift
Labels: feat

#47 [Design/#46] watch app 디자인 변경
  SeSACTHON_App/SeSACTHON_Watch Watch App/ContentView.swift
Labels: Design

#49 [Design/#48] TopProfile 디자인 변경
  SeSACTHON_App/SeSACTHON_App/Global/Components/TopProfileView.swift
Labels: Design

#51 [design/#50] watch app design 변경 (배치만 수정, 세부수정 필요)
  SeSACTHON_App/SeSACTHON_App.xcodeproj/project.pbxproj
  SeSACTHON_App/SeSACTHON_App/Global/Extension/ColorExtension.swift
  SeSACTHON_App/SeSACTHON_Watch Watch App/ReportView.swift
  SeSACTHON_App/SeSACTHON_Watch Watch App/RunningEndView.swift
  SeSACTHON_App/SeSACTHON_Watch Watch App/RunningTimeView.swift
  SeSACTHON_App/SeSACTHON_Watch Watch App/RunningView.swift
  SeSACTHON_App/SeSACTHON_Watch Watch App/SeSACTHON_WatchApp.swift
  SeSACTHON_App/SeSACTHON_Watch Watch App/StartView.swift
Labels: Design

#52 [Feat/#38] 3초 Countdown 구현, 애니메이션 구현
  SeSACTHON_App/SeSACTHON_App.xcodeproj/project.pbxproj
  SeSACTHON_App/SeSACTHON_App/View/MainRunView.swift
Labels: feat

#54 [Design/#53] Watch app design ver2 완료 - 기능추가 필요
  SeSACTHON_App/SeSACTHON_App.xcodeproj/project.pbxproj
  SeSACTHON_App/SeSACTHON_App/Global/Extension/ColorExtension.swift
  SeSACTHON_App/SeSACTHON_App/Resources/Assets.xcassets/icon _bell outline_.imageset/Contents.json
  SeSACTHON_App/SeSACTHON_App/Resources/Assets.xcassets/icon _bell outline_.imageset/icon _bell outline_.png
  SeSACTHON_App/SeSACTHON_App/Resources/Assets.xcassets/icon _bell outline_.imageset/icon _bell outline_@2x.png
  SeSACTHON_App/SeSACTHON_App/Resources/Assets.xcassets/icon _bell outline_.imageset/icon _bell outline_@3x.png
  SeSACTHON_App/SeSACTHON_Watch Watch App/Assets.xcassets/AccentColor.colorset/Contents.json
  SeSACTHON_App/SeSACTHON_Watch Watch App/Assets.xcassets/AppIcon.appiconset/Contents.json
  SeSACTHON_App/SeSACTHON_Watch Watch App/Assets.xcassets/Contents.json
  SeSACTHON_App/SeSACTHON_Watch Watch App/ContentView.swift
  SeSACTHON_App/SeSACTHON_Watch Watch App/ReportView.swift
  SeSACTHON_App/SeSACTHON_Watch Watch App/RunningEndView.swift
  SeSACTHON_App/SeSACTHON_Watch Watch App/RunningResultView.swift
  SeSACTHON_App/SeSACTHON_Watch Watch App/RunningTimeView.swift
  SeSACTHON_App/SeSACTHON_Watch Watch App/RunningView.swift
  SeSACTHON_App/SeSACTHON_Watch Watch App/SeSACTHON_WatchApp.swift
  SeSACTHON_App/SeSACTHON_Watch Watch App/StartView.swift
  SeSACTHON_App/SeSACTHON_Watch Watch App/watchBackButton.swift
Labels: Design

#56 [Design/#55] HomeView 간단한 디자인 완성
  SeSACTHON_App/SeSACTHON_App.xcodeproj/project.pbxproj
  SeSACTHON_App/SeSACTHON_App/View/ContentView.swift
  SeSACTHON_App/SeSACTHON_App/View/HomeView.swift
Labels: Design

#57 Radin feat/#39
  SeSACTHON_App/SeSACTHON-App-Info.plist
  SeSACTHON_App/SeSACTHON_App.xcodeproj/project.pbxproj
  SeSACTHON_App/SeSACTHON_App/Global/HealthDataManager.swift
  SeSACTHON_App/SeSACTHON_App/Global/Utilities/HealthKitSupport+Strings.swift
  SeSACTHON_App/SeSACTHON_App/Global/Utilities/HealthKitSupport.swift
  SeSACTHON_App/SeSACTHON_App/Resources/Assets.xcassets/Colors/Darkgray.colorset/Contents.json
  SeSACTHON_App/SeSACTHON_App/SeSACTHON_App.entitlements
  SeSACTHON_App/SeSACTHON_App/SeSACTHON_AppApp.swift
  SeSACTHON_App/SeSACTHON_App/View/MainRunView.swift
  SeSACTHON_App/SeSACTHON_App/View/MainRunningView.swift
Labels: feat

#61 [Design/#60] HomeView 변경 & ProfileView 생성 (HomeView 디자인 만나서 이야기 해볼것)
  SeSACTHON_App/SeSACTHON_App.xcodeproj/project.pbxproj
  SeSACTHON_App/SeSACTHON_App/Global/Components/YoutubeView.swift
  SeSACTHON_App/SeSACTHON_App/View/HomeView.swift
  SeSACTHON_App/SeSACTHON_App/View/ProfileView.swift
Labels: Design

#65 [Feat/#64] 현재위치 주소 문자로 받아오기 & 화면에 표시
  SeSACTHON_App/SeSACTHON_App.xcodeproj/project.pbxproj
  SeSACTHON_App/SeSACTHON_App/Global/LocationDataManager.swift
  SeSACTHON_App/SeSACTHON_App/View/MainMapView.swift
Labels: feat

#67 [Chore/#66] HomeView 콘텐츠 변경, Profileview 디자인
  SeSACTHON_App/SeSACTHON_App.xcodeproj/project.pbxproj
  SeSACTHON_App/SeSACTHON_App/Resources/Assets.xcassets/NewsSample1.imageset/Contents.json
  SeSACTHON_App/SeSACTHON_App/Resources/Assets.xcassets/NewsSample1.imageset/NewsSample1.png
  SeSACTHON_App/SeSACTHON_App/Resources/Assets.xcassets/NewsSample2.imageset/Contents.json
  SeSACTHON_App/SeSACTHON_App/Resources/Assets.xcassets/NewsSample2.imageset/NewSample2.png
  SeSACTHON_App/SeSACTHON_App/Resources/Assets.xcassets/NewsSample3.imageset/Contents.json
  SeSACTHON_App/SeSACTHON_App/Resources/Assets.xcassets/NewsSample3.imageset/NewsSample3.jpg
  SeSACTHON_App/SeSACTHON_App/Resources/Assets.xcassets/NewsSample4.imageset/Contents.json
  SeSACTHON_App/SeSACTHON_App/Resources/Assets.xcassets/NewsSample4.imageset/NewsSample4.png
  SeSACTHON_App/SeSACTHON_App/Resources/Assets.xcassets/이.imageset/Rectangle 136@2x.png
  SeSACTHON_App/SeSACTHON_App/SeSACTHON_AppApp.swift
  SeSACTHON_App/SeSACTHON_App/View/ContentView.swift
  SeSACTHON_App/SeSACTHON_App/View/HomeView.swift
  SeSACTHON_App/SeSACTHON_App/View/ProfileView.swift
Labels: chore

#71 [Chore/#67] HomeView 수정
  SeSACTHON_App/SeSACTHON-App-Info.plist
  SeSACTHON_App/SeSACTHON_App.xcodeproj/project.pbxproj
  SeSACTHON_App/SeSACTHON_App/View/HomeView.swift
Labels: chore

#73 [Feat/#72] Map Search 기능 추가
  SeSACTHON_App/SeSACTHON_App/View/MainMapView.swift
Labels: feat

#75 [Design/#74] Watch Design 변경
  SeSACTHON_App/SeSACTHON_Watch Watch App/ReportView.swift
  SeSACTHON_App/SeSACTHON_Watch Watch App/RunningEndView.swift
  SeSACTHON_App/SeSACTHON_Watch Watch App/RunningResultView.swift
  SeSACTHON_App/SeSACTHON_Watch Watch App/RunningTimeView.swift
  SeSACTHON_App/SeSACTHON_Watch Watch App/RunningView.swift
  SeSACTHON_App/SeSACTHON_Watch Watch App/SeSACTHON_WatchApp.swift
  SeSACTHON_App/SeSACTHON_Watch Watch App/StartView.swift
Labels: Design

#76 Radin feat/#58
  SeSACTHON_App/SeSACTHON_App.xcodeproj/project.pbxproj
  SeSACTHON_App/SeSACTHON_App/Global/Components/Extra/Blur.swift
  SeSACTHON_App/SeSACTHON_App/Global/Components/Extra/InfoView.swift
  SeSACTHON_App/SeSACTHON_App/Global/Components/Extra/PermissionView.swift
  SeSACTHON_App/SeSACTHON_App/Global/Components/Extra/RunListView.swift
  SeSACTHON_App/SeSACTHON_App/Global/Components/Extra/View.swift
  SeSACTHON_App/SeSACTHON_App/Global/Components/FloatingButtons.swift
  SeSACTHON_App/SeSACTHON_App/Global/Components/MapView.swift
  SeSACTHON_App/SeSACTHON_App/Global/Components/WorkoutBar.swift
  SeSACTHON_App/SeSACTHON_App/Global/Extension/CLLocation.swift
  SeSACTHON_App/SeSACTHON_App/Global/Extension/CLLocationCoordinate2D.swift
  SeSACTHON_App/SeSACTHON_App/Global/Extension/Date.swift
  SeSACTHON_App/SeSACTHON_App/Global/HealthDataManager.swift
  SeSACTHON_App/SeSACTHON_App/Global/Utilities/HKHelper.swift
  SeSACTHON_App/SeSACTHON_App/Global/Utilities/Haptics.swift
  SeSACTHON_App/SeSACTHON_App/Global/Utilities/HealthKitSupport+Strings.swift
  SeSACTHON_App/SeSACTHON_App/Global/Utilities/HealthKitSupport.swift
  SeSACTHON_App/SeSACTHON_App/Model/MyMapError.swift
  SeSACTHON_App/SeSACTHON_App/Model/Workout.swift
  SeSACTHON_App/SeSACTHON_App/Model/WorkoutFilter.swift
  SeSACTHON_App/SeSACTHON_App/Model/WorkoutType.swift
  SeSACTHON_App/SeSACTHON_App/Model/WorkoutViewModel.swift
  SeSACTHON_App/SeSACTHON_App/SeSACTHON_AppApp.swift
  SeSACTHON_App/SeSACTHON_App/View/MainRunView.swift
  SeSACTHON_App/SeSACTHON_App/View/MainRunningView.swift
  SeSACTHON_App/SeSACTHON_App/View/RootView.swift
Labels: feat

#80 [Refactor/#79] 디자인 미세 수정
  SeSACTHON_App/SeSACTHON_App.xcodeproj/project.pbxproj
  SeSACTHON_App/SeSACTHON_App/Global/Components/TopProfileView.swift
  SeSACTHON_App/SeSACTHON_App/Global/Extension/Extra/Blur.swift
  SeSACTHON_App/SeSACTHON_App/Global/Extension/Extra/InfoView.swift
  SeSACTHON_App/SeSACTHON_App/Global/Extension/Extra/PermissionView.swift
  SeSACTHON_App/SeSACTHON_App/Global/Extension/Extra/RunListView.swift
  SeSACTHON_App/SeSACTHON_App/Global/Extension/Extra/View.swift
  SeSACTHON_App/SeSACTHON_App/View/HomeView.swift
  SeSACTHON_App/SeSACTHON_App/View/MainMapView.swift
  SeSACTHON_App/SeSACTHON_App/View/MainRunView.swift
  SeSACTHON_App/SeSACTHON_App/View/ProfileView.swift
  SeSACTHON_App/SeSACTHON_App/View/RunEndView.swift
Labels: Refactor

#82 [Feat/#81] DB 모델 추가
  SeSACTHON_App/SeSACTHON_App.xcodeproj/project.pbxproj
  SeSACTHON_App/SeSACTHON_App/Global/Components/PlaceAnnotationView.swift
  SeSACTHON_App/SeSACTHON_App/Global/Extension/ViewExtension.swift
  SeSACTHON_App/SeSACTHON_App/Model/Dao/DangerInfoMO.swift
  SeSACTHON_App/SeSACTHON_App/Model/Dao/MemberMO.swift
  SeSACTHON_App/SeSACTHON_App/Model/Dao/PlaceMO.swift
  SeSACTHON_App/SeSACTHON_App/Model/Dao/RunningInfo.swift
  SeSACTHON_App/SeSACTHON_App/View/MainMapView.swift
  SeSACTHON_App/SeSACTHON_App/View/ProfileView.swift
Labels: feat

#86 [Chore/#85] 디비 모델 추가
  SeSACTHON_App/SeSACTHON_App.xcodeproj/project.pbxproj
  SeSACTHON_App/SeSACTHON_App/Global/Components/PlaceAnnotationView.swift
  SeSACTHON_App/SeSACTHON_App/Model/DAO/DangerInfoMO.swift
  SeSACTHON_App/SeSACTHON_App/Model/DAO/MemberMO.swift
  SeSACTHON_App/SeSACTHON_App/Model/DAO/RunningInfo.swift
  SeSACTHON_App/SeSACTHON_App/View/MainMapView.swift
Labels: chore

#88 [Chore/#87] Profile & PlaceAnnotation DB 연동 대비 작업 완료
  SeSACTHON_App/SeSACTHON_App/Global/Components/PlaceAnnotationView.swift
  SeSACTHON_App/SeSACTHON_App/Global/Components/TopProfileView.swift
  SeSACTHON_App/SeSACTHON_App/Global/Extension/ViewExtension.swift
  SeSACTHON_App/SeSACTHON_App/View/MainMapView.swift
  SeSACTHON_App/SeSACTHON_App/View/ProfileView.swift
Labels: chore

#90 [Design/#89] MainRun Design 수정
  SeSACTHON_App/SeSACTHON_App/Global/Components/CustomMapView.swift
  SeSACTHON_App/SeSACTHON_App/Global/Components/TopProfileView.swift
  SeSACTHON_App/SeSACTHON_App/Resources/Assets.xcassets/RunCamera.imageset/Contents.json
  SeSACTHON_App/SeSACTHON_App/Resources/Assets.xcassets/RunCamera.imageset/RunCamera.png
  SeSACTHON_App/SeSACTHON_App/Resources/Assets.xcassets/RunCamera.imageset/RunCamera@2x.png
  SeSACTHON_App/SeSACTHON_App/Resources/Assets.xcassets/RunCamera.imageset/RunCamera@3x.png
  SeSACTHON_App/SeSACTHON_App/Resources/Assets.xcassets/RunLocation.imageset/Contents.json
  SeSACTHON_App/SeSACTHON_App/Resources/Assets.xcassets/RunLocation.imageset/RunLocation.png
  SeSACTHON_App/SeSACTHON_App/Resources/Assets.xcassets/RunLocation.imageset/RunLocation@2x.png
  SeSACTHON_App/SeSACTHON_App/Resources/Assets.xcassets/RunLocation.imageset/RunLocation@3x.png
  SeSACTHON_App/SeSACTHON_App/Resources/Assets.xcassets/RunSetting.imageset/Contents.json
  SeSACTHON_App/SeSACTHON_App/Resources/Assets.xcassets/RunSetting.imageset/RunSetting.png
  SeSACTHON_App/SeSACTHON_App/Resources/Assets.xcassets/RunSetting.imageset/RunSetting@2x.png
  SeSACTHON_App/SeSACTHON_App/Resources/Assets.xcassets/RunSetting.imageset/RunSetting@3x.png
  SeSACTHON_App/SeSACTHON_App/View/MainRunView.swift
Labels: Design

#92 [Design/#91] HomeView 페이지 탭 개선
  SeSACTHON_App/SeSACTHON_App/Global/Components/CustomCameraView.swift
  SeSACTHON_App/SeSACTHON_App/View/HomeView.swift
Labels: Design

#94 [Feat/#93] Test API - DangerInfo
  SeSACTHON_App/SeSACTHON_App/Global/Components/PlaceAnnotationView.swift
  SeSACTHON_App/SeSACTHON_App/Global/Extension/ViewExtension.swift
  SeSACTHON_App/SeSACTHON_App/Model/DAO/DangerInfoMO.swift
  SeSACTHON_App/SeSACTHON_App/View/MainMapView.swift
Labels: feat

#96 [Refactor/#95] DB 데이터셋 변경, MainMap API 연동
  SeSACTHON_App/SeSACTHON_App/Global/Extension/ViewExtension.swift
  SeSACTHON_App/SeSACTHON_App/Model/DAO/DangerInfoMO.swift
  SeSACTHON_App/SeSACTHON_App/Model/DAO/MemberMO.swift
  SeSACTHON_App/SeSACTHON_App/Model/DAO/RunningInfo.swift
  SeSACTHON_App/SeSACTHON_App/View/MainMapView.swift
  SeSACTHON_App/SeSACTHON_App/View/ProfileView.swift
Labels: Refactor

#98 [Feat/#97] Apple Login시 데이터 API로 저장하는 기능 추가
  SeSACTHON_App/SeSACTHON_App/View/LoginView.swift
Labels: feat

#101 [Feat/#99] Running data (RunEnd & Profile) API 연동
  SeSACTHON_App/Podfile
  SeSACTHON_App/Podfile.lock
  SeSACTHON_App/SeSACTHON_App.xcodeproj/xcshareddata/xcschemes/SeSACTHON_App.xcscheme
  SeSACTHON_App/SeSACTHON_App.xcodeproj/xcshareddata/xcschemes/SeSACTHON_Watch Watch App.xcscheme
  SeSACTHON_App/SeSACTHON_App/Model/DAO/RunningInfo.swift
  SeSACTHON_App/SeSACTHON_App/View/ProfileView.swift
  SeSACTHON_App/SeSACTHON_App/View/RunEndView.swift
Labels: feat

#104 [Feat/#103] 닉네임 변경 기능 추가 & Profile Member API 연동
  SeSACTHON_App/SeSACTHON_App/Global/Extension/ViewExtension.swift
  SeSACTHON_App/SeSACTHON_App/Model/DAO/MemberMO.swift
  SeSACTHON_App/SeSACTHON_App/View/LoginView.swift
  SeSACTHON_App/SeSACTHON_App/View/ProfileView.swift
Labels: feat

#106 Radin design/#59
  SeSACTHON_App/SeSACTHON-App-Info.plist
  SeSACTHON_App/SeSACTHON_App.xcodeproj/project.pbxproj
  SeSACTHON_App/SeSACTHON_App/Global/Components/CustomCameraView.swift
  SeSACTHON_App/SeSACTHON_App/Global/Components/MapView.swift
  SeSACTHON_App/SeSACTHON_App/Model/CameraModel.swift
  SeSACTHON_App/SeSACTHON_App/Resources/Assets.xcassets/camerabig.imageset/Contents.json
  SeSACTHON_App/SeSACTHON_App/Resources/Assets.xcassets/camerabig.imageset/camerabig.png
  SeSACTHON_App/SeSACTHON_App/Resources/Assets.xcassets/send.imageset/Contents.json
  SeSACTHON_App/SeSACTHON_App/Resources/Assets.xcassets/send.imageset/send.png
  SeSACTHON_App/SeSACTHON_App/View/MainRunView.swift
  SeSACTHON_App/SeSACTHON_App/View/ReportSubmitView.swift
  SeSACTHON_App/SeSACTHON_App/View/RootView.swift
Labels: Design

#108 [Deisgn/#107] LaunchScreen 변경
  SeSACTHON_App/SeSACTHON-App-Info.plist
  SeSACTHON_App/SeSACTHON_App.xcodeproj/project.pbxproj
  SeSACTHON_App/SeSACTHON_App/Resources/Assets.xcassets/LaunchScreen.imageset/Contents.json
  SeSACTHON_App/SeSACTHON_App/Resources/Assets.xcassets/LaunchScreen.imageset/LaunchScreen.png
  SeSACTHON_App/SeSACTHON_App/Resources/Assets.xcassets/LaunchScreen.imageset/LaunchScreen@2x.png
  SeSACTHON_App/SeSACTHON_App/Resources/Assets.xcassets/LaunchScreen.imageset/LaunchScreen@3x.png
  SeSACTHON_App/SeSACTHON_App/Resources/Assets.xcassets/LoadingImg.imageset/LoadingImg.png
  SeSACTHON_App/SeSACTHON_App/Resources/Assets.xcassets/LoadingImg.imageset/LoadingImg@2x.png
  SeSACTHON_App/SeSACTHON_App/Resources/Assets.xcassets/LoadingImg.imageset/LoadingImg@3x.png
  SeSACTHON_App/SeSACTHON_App/Resources/Assets.xcassets/LoginScreen.imageset/Contents.json
  SeSACTHON_App/SeSACTHON_App/Resources/Assets.xcassets/LoginScreen.imageset/LoginScreen.png
  SeSACTHON_App/SeSACTHON_App/Resources/Assets.xcassets/LoginScreen.imageset/LoginScreen2x.png
  SeSACTHON_App/SeSACTHON_App/Resources/Assets.xcassets/LoginScreen.imageset/LoginScreen@3x.png
  SeSACTHON_App/SeSACTHON_App/SeSACTHON_AppApp.swift
  SeSACTHON_App/SeSACTHON_App/View/LoginView.swift
Labels: Design

#110 [Design/#109] 맵 검색화면 디자인 변경
  SeSACTHON_App/SeSACTHON_App.xcodeproj/project.pbxproj
  SeSACTHON_App/SeSACTHON_App/View/MainMapView.swift
Labels: Design

#111 Radin feat/#77
  SeSACTHON_App/SeSACTHON_App/Global/Components/FloatingButtons.swift
  SeSACTHON_App/SeSACTHON_App/Global/Components/TopProfileView.swift
  SeSACTHON_App/SeSACTHON_App/Model/Workout.swift
  SeSACTHON_App/SeSACTHON_App/Model/WorkoutType.swift
  SeSACTHON_App/SeSACTHON_App/Model/WorkoutViewModel.swift
  SeSACTHON_App/SeSACTHON_App/View/MainRunView.swift
  SeSACTHON_App/SeSACTHON_App/View/MainRunningView.swift
  SeSACTHON_App/SeSACTHON_App/View/RootView.swift
  SeSACTHON_App/SeSACTHON_App/View/RunEndView.swift
Labels: feat

#113 [Setting/#112] watch app pod setting
  SeSACTHON_App/Podfile
  SeSACTHON_App/Podfile.lock
  SeSACTHON_App/SeSACTHON_App.xcodeproj/project.pbxproj
Labels: Setting

#117 [Feat/#116] Camera 방식 변경 (기능 미완성)
  SeSACTHON_App/SeSACTHON_App.xcodeproj/project.pbxproj
  SeSACTHON_App/SeSACTHON_App/Model/SUImagePicker.swift
  SeSACTHON_App/SeSACTHON_App/View/MainRunView.swift
  SeSACTHON_App/SeSACTHON_App/View/MainRunningView.swift
Labels: feat

#121 [Design/#118] 워치 디자인 수정 작업
  SeSACTHON_App/SeSACTHON_App/Resources/Assets.xcassets/construction_white.imageset/Contents.json
  SeSACTHON_App/SeSACTHON_App/Resources/Assets.xcassets/construction_white.imageset/construction_white.png
  SeSACTHON_App/SeSACTHON_App/Resources/Assets.xcassets/construction_white.imageset/construction_white@2x.png
  SeSACTHON_App/SeSACTHON_App/Resources/Assets.xcassets/construction_white.imageset/construction_white@3x.png
  SeSACTHON_App/SeSACTHON_App/Resources/Assets.xcassets/elevation_white.imageset/Contents.json
  SeSACTHON_App/SeSACTHON_App/Resources/Assets.xcassets/elevation_white.imageset/elevation_white.png
  SeSACTHON_App/SeSACTHON_App/Resources/Assets.xcassets/elevation_white.imageset/elevation_white@2x.png
  SeSACTHON_App/SeSACTHON_App/Resources/Assets.xcassets/elevation_white.imageset/elevation_white@3x.png
  SeSACTHON_App/SeSACTHON_App/Resources/Assets.xcassets/narrow_white.imageset/Contents.json
  SeSACTHON_App/SeSACTHON_App/Resources/Assets.xcassets/narrow_white.imageset/narrow_white.png
  SeSACTHON_App/SeSACTHON_App/Resources/Assets.xcassets/narrow_white.imageset/narrow_white@2x.png
  SeSACTHON_App/SeSACTHON_App/Resources/Assets.xcassets/narrow_white.imageset/narrow_white@3x.png
  SeSACTHON_App/SeSACTHON_App/Resources/Assets.xcassets/step_white.imageset/Contents.json
  SeSACTHON_App/SeSACTHON_App/Resources/Assets.xcassets/step_white.imageset/step_white.png
  SeSACTHON_App/SeSACTHON_App/Resources/Assets.xcassets/step_white.imageset/step_white@2x.png
  SeSACTHON_App/SeSACTHON_App/Resources/Assets.xcassets/step_white.imageset/step_white@3x.png
  SeSACTHON_App/SeSACTHON_Watch Watch App/ReportView.swift
  SeSACTHON_App/SeSACTHON_Watch Watch App/RunningView.swift
Labels: Design

#122 [Feat/#78] 칼로리 로직 추가 및 UI 일부 수정
  SeSACTHON_App/SeSACTHON_App.xcodeproj/project.pbxproj
  SeSACTHON_App/SeSACTHON_App/Global/Components/FloatingButtons.swift
  SeSACTHON_App/SeSACTHON_App/Global/Components/WorkoutBar.swift
  SeSACTHON_App/SeSACTHON_App/Global/Utilities/HKHelper.swift
  SeSACTHON_App/SeSACTHON_App/Model/Workout.swift
  SeSACTHON_App/SeSACTHON_App/Model/WorkoutType.swift
  SeSACTHON_App/SeSACTHON_App/Model/WorkoutViewModel.swift
  SeSACTHON_App/SeSACTHON_App/Resources/Assets.xcassets/Colors/#222222.colorset/Contents.json
  SeSACTHON_App/SeSACTHON_App/View/HomeView.swift
  SeSACTHON_App/SeSACTHON_App/View/MainRunView.swift
  SeSACTHON_App/SeSACTHON_App/View/MainRunningView.swift
  SeSACTHON_App/SeSACTHON_App/View/RootView.swift
  SeSACTHON_App/SeSACTHON_App/View/RunEndView.swift
Labels: feat

#124 [Design/#123] Placeannotation 아이콘 버그 수정
  SeSACTHON_App/SeSACTHON_App.xcodeproj/project.pbxproj
Labels: Design

#127 [Design/#125] 위험요소 이미지 보여주기 구현
  SeSACTHON_App/SeSACTHON-Watch-Watch-App-Info.plist
  SeSACTHON_App/SeSACTHON_App.xcodeproj/project.pbxproj
  SeSACTHON_App/SeSACTHON_App/Global/Components/PlaceAnnotationView.swift
  SeSACTHON_App/SeSACTHON_App/View/RunEndView.swift
Labels: Design

#134 [Feat/#126] 런 페이스 계산 & UI 수정
  SeSACTHON_App/SeSACTHON_App/Global/Components/WorkoutBar.swift
  SeSACTHON_App/SeSACTHON_App/Global/Extension/Extra/InfoView.swift
  SeSACTHON_App/SeSACTHON_App/Model/WorkoutViewModel.swift
  SeSACTHON_App/SeSACTHON_App/View/MainRunningView.swift
  SeSACTHON_App/SeSACTHON_App/View/RunEndView.swift
Labels: feat

#147 [Design/#146] 장애물 사진 & 위치 전송 기능 구현 완
  SeSACTHON_App/SeSACTHON_App/Global/Extension/ViewExtension.swift
  SeSACTHON_App/SeSACTHON_App/Resources/Assets.xcassets/CameraButton.imageset/CameraButton.png
  SeSACTHON_App/SeSACTHON_App/Resources/Assets.xcassets/CameraButton.imageset/CameraButton@2x.png
  SeSACTHON_App/SeSACTHON_App/Resources/Assets.xcassets/CameraButton.imageset/CameraButton@3x.png
  SeSACTHON_App/SeSACTHON_App/Resources/Assets.xcassets/CameraButton.imageset/Contents.json
  SeSACTHON_App/SeSACTHON_App/Resources/Assets.xcassets/SendButton.imageset/Contents.json
  SeSACTHON_App/SeSACTHON_App/Resources/Assets.xcassets/SendButton.imageset/SendButton.png
  SeSACTHON_App/SeSACTHON_App/Resources/Assets.xcassets/SendButton.imageset/SendButton@2x.png
  SeSACTHON_App/SeSACTHON_App/Resources/Assets.xcassets/SendButton.imageset/SendButton@3x.png
  SeSACTHON_App/SeSACTHON_App/View/MainRunView.swift
  SeSACTHON_App/SeSACTHON_App/View/MainRunningView.swift
  SeSACTHON_App/SeSACTHON_App/View/ProfileView.swift
Labels: Design

#148 [feat/#135] 코스 이미지 앨범 저장, 변수에 저장 기능 구현
  SeSACTHON_App/SeSACTHON_App/Global/Components/WorkoutBar.swift
  SeSACTHON_App/SeSACTHON_App/Model/Workout.swift
  SeSACTHON_App/SeSACTHON_App/Model/WorkoutViewModel.swift
  SeSACTHON_App/SeSACTHON_App/View/MainRunningView.swift
  SeSACTHON_App/SeSACTHON_App/View/RunEndView.swift
Labels: feat

#150 [design/#115] WorkoutBar, HomeView, RunView UI 수정
  SeSACTHON_App/SeSACTHON_App/Global/Components/WorkoutBar.swift
  SeSACTHON_App/SeSACTHON_App/View/HomeView.swift
  SeSACTHON_App/SeSACTHON_App/View/MainRunView.swift
  SeSACTHON_App/SeSACTHON_App/View/MainRunningView.swift
Labels: Design

#153 [Feat/#149] 러닝 기록 저장 기능 구현 (칼로리는 0, 거리는 km 단위로 바꿔줘야함)
  SeSACTHON_App/SeSACTHON_App.xcodeproj/project.pbxproj
  SeSACTHON_App/SeSACTHON_App/View/RunEndView.swift
Labels: feat

#155 [Feat/#154] 신고 시 total_count + 1
  SeSACTHON_App/SeSACTHON_App/View/MainRunView.swift
  SeSACTHON_App/SeSACTHON_App/View/MainRunningView.swift
Labels: feat

#159 [Feat/#158] RunEnd 총 도움 갯수 연동
  SeSACTHON_App/SeSACTHON_App.xcodeproj/project.pbxproj
  SeSACTHON_App/SeSACTHON_App/View/RunEndView.swift
Labels: feat

#163 [feat/#136] 러닝 타임 일시 정지, UI 수정
  SeSACTHON_App/SeSACTHON_App/Global/Components/WorkoutBar.swift
  SeSACTHON_App/SeSACTHON_App/Model/WorkoutViewModel.swift
  SeSACTHON_App/SeSACTHON_App/View/MainRunView.swift
  SeSACTHON_App/SeSACTHON_App/View/MainRunningView.swift
  SeSACTHON_App/SeSACTHON_App/View/RunEndView.swift
Labels: feat

#166 [Feat/#162] RunViews 프로파일 이미지 적용
  SeSACTHON_App/SeSACTHON_App.xcodeproj/project.pbxproj
  SeSACTHON_App/SeSACTHON_App.xcodeproj/xcshareddata/xcschemes/SeSACTHON_Watch Watch App.xcscheme
  SeSACTHON_App/SeSACTHON_App/Global/Components/TopProfileView.swift
  SeSACTHON_App/SeSACTHON_App/View/GlobalProfileImage.swift
  SeSACTHON_App/SeSACTHON_App/View/RunEndView.swift
Labels: feat

#169 [Feat/#167] helpCount 계산 기능
  SeSACTHON_App/SeSACTHON_App.xcodeproj/project.pbxproj
  SeSACTHON_App/SeSACTHON_App/View/MainRunView.swift
  SeSACTHON_App/SeSACTHON_App/View/MainRunningView.swift
  SeSACTHON_App/SeSACTHON_App/View/RunEndView.swift
Labels: feat

#171 [Design/#170] SubmitView 디자인 수정 - (화면 밀림, 아이콘 제대로 표시)
  SeSACTHON_App/SeSACTHON_App/Global/Components/RunningRepertSubmitView.swift
  SeSACTHON_App/SeSACTHON_App/View/ReportSubmitView.swift
Labels: Design

#173 [Design/#172] 앱 아이콘 추가
  SeSACTHON_App/SeSACTHON_App/Resources/Assets.xcassets/AppIcon.appiconset/100.png
  SeSACTHON_App/SeSACTHON_App/Resources/Assets.xcassets/AppIcon.appiconset/102.png
  SeSACTHON_App/SeSACTHON_App/Resources/Assets.xcassets/AppIcon.appiconset/1024.png
  SeSACTHON_App/SeSACTHON_App/Resources/Assets.xcassets/AppIcon.appiconset/114.png
  SeSACTHON_App/SeSACTHON_App/Resources/Assets.xcassets/AppIcon.appiconset/120.png
  SeSACTHON_App/SeSACTHON_App/Resources/Assets.xcassets/AppIcon.appiconset/128.png
  SeSACTHON_App/SeSACTHON_App/Resources/Assets.xcassets/AppIcon.appiconset/144.png
  SeSACTHON_App/SeSACTHON_App/Resources/Assets.xcassets/AppIcon.appiconset/152.png
  SeSACTHON_App/SeSACTHON_App/Resources/Assets.xcassets/AppIcon.appiconset/16.png
  SeSACTHON_App/SeSACTHON_App/Resources/Assets.xcassets/AppIcon.appiconset/167.png
  SeSACTHON_App/SeSACTHON_App/Resources/Assets.xcassets/AppIcon.appiconset/172.png
  SeSACTHON_App/SeSACTHON_App/Resources/Assets.xcassets/AppIcon.appiconset/180.png
  SeSACTHON_App/SeSACTHON_App/Resources/Assets.xcassets/AppIcon.appiconset/196.png
  SeSACTHON_App/SeSACTHON_App/Resources/Assets.xcassets/AppIcon.appiconset/20.png
  SeSACTHON_App/SeSACTHON_App/Resources/Assets.xcassets/AppIcon.appiconset/216.png
  SeSACTHON_App/SeSACTHON_App/Resources/Assets.xcassets/AppIcon.appiconset/256.png
  SeSACTHON_App/SeSACTHON_App/Resources/Assets.xcassets/AppIcon.appiconset/29.png
  SeSACTHON_App/SeSACTHON_App/Resources/Assets.xcassets/AppIcon.appiconset/32.png
  SeSACTHON_App/SeSACTHON_App/Resources/Assets.xcassets/AppIcon.appiconset/40.png
  SeSACTHON_App/SeSACTHON_App/Resources/Assets.xcassets/AppIcon.appiconset/48.png
  SeSACTHON_App/SeSACTHON_App/Resources/Assets.xcassets/AppIcon.appiconset/50.png
  SeSACTHON_App/SeSACTHON_App/Resources/Assets.xcassets/AppIcon.appiconset/512.png
  SeSACTHON_App/SeSACTHON_App/Resources/Assets.xcassets/AppIcon.appiconset/55.png
  SeSACTHON_App/SeSACTHON_App/Resources/Assets.xcassets/AppIcon.appiconset/57.png
  SeSACTHON_App/SeSACTHON_App/Resources/Assets.xcassets/AppIcon.appiconset/58.png
  SeSACTHON_App/SeSACTHON_App/Resources/Assets.xcassets/AppIcon.appiconset/60.png
  SeSACTHON_App/SeSACTHON_App/Resources/Assets.xcassets/AppIcon.appiconset/64.png
  SeSACTHON_App/SeSACTHON_App/Resources/Assets.xcassets/AppIcon.appiconset/66.png
  SeSACTHON_App/SeSACTHON_App/Resources/Assets.xcassets/AppIcon.appiconset/72.png
  SeSACTHON_App/SeSACTHON_App/Resources/Assets.xcassets/AppIcon.appiconset/76.png
  SeSACTHON_App/SeSACTHON_App/Resources/Assets.xcassets/AppIcon.appiconset/80.png
  SeSACTHON_App/SeSACTHON_App/Resources/Assets.xcassets/AppIcon.appiconset/87.png
  SeSACTHON_App/SeSACTHON_App/Resources/Assets.xcassets/AppIcon.appiconset/88.png
  SeSACTHON_App/SeSACTHON_App/Resources/Assets.xcassets/AppIcon.appiconset/92.png
  SeSACTHON_App/SeSACTHON_App/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json
Labels: Design

#174 [feat/#164] 코스 이미지 변수 수정
  SeSACTHON_App/SeSACTHON_App/Model/Workout.swift
  SeSACTHON_App/SeSACTHON_App/Model/WorkoutViewModel.swift
  SeSACTHON_App/SeSACTHON_App/View/MainRunView.swift
  SeSACTHON_App/SeSACTHON_App/View/MainRunningView.swift
  SeSACTHON_App/SeSACTHON_App/View/RunEndView.swift
Labels: feat

#176 [Design/#175] 스플래시 로고 변경
  SeSACTHON_App/SeSACTHON-App-Info.plist
Labels: Design

#178 [feat] helpcount를 workbar에 연결
  SeSACTHON_App/SeSACTHON_App/Global/Components/WorkoutBar.swift
  SeSACTHON_App/SeSACTHON_App/View/MainRunningView.swift
Labels: feat

#181 [Chore/#180] Running distance km 저장되게
  SeSACTHON_App/SeSACTHON_App/View/RunEndView.swift
Labels: chore

#184 Radin feat/#179
  SeSACTHON_App/SeSACTHON_App.xcodeproj/project.pbxproj
  SeSACTHON_App/SeSACTHON_App/Global/Components/RunningRepertSubmitView.swift
  SeSACTHON_App/SeSACTHON_App/Global/Components/WorkoutBar.swift
  SeSACTHON_App/SeSACTHON_App/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json
  SeSACTHON_App/SeSACTHON_App/View/MainRunView.swift
  SeSACTHON_App/SeSACTHON_App/View/MainRunningView.swift
  SeSACTHON_App/SeSACTHON_App/View/ReportSubmitView.swift
  SeSACTHON_App/SeSACTHON_App/View/RunEndView.swift
Labels: feat

#192 [Design/#190] 전체적인 디자인 디테일 수정
  SeSACTHON_App/SeSACTHON_App.xcodeproj/project.pbxproj
  SeSACTHON_App/SeSACTHON_App/Global/Components/RunningRepertSubmitView.swift
  SeSACTHON_App/SeSACTHON_App/Resources/Assets.xcassets/FinalCamera.imageset/Contents.json
  SeSACTHON_App/SeSACTHON_App/Resources/Assets.xcassets/FinalCamera.imageset/FinalCamera.png
  SeSACTHON_App/SeSACTHON_App/Resources/Assets.xcassets/FinalCamera.imageset/FinalCamera@2x.png
  SeSACTHON_App/SeSACTHON_App/Resources/Assets.xcassets/FinalCamera.imageset/FinalCamera@3x.png
  SeSACTHON_App/SeSACTHON_App/Resources/Assets.xcassets/FinalLocation.imageset/Contents.json
  SeSACTHON_App/SeSACTHON_App/Resources/Assets.xcassets/FinalLocation.imageset/FinalLocation.png
  SeSACTHON_App/SeSACTHON_App/Resources/Assets.xcassets/FinalLocation.imageset/FinalLocation@2x.png
  SeSACTHON_App/SeSACTHON_App/Resources/Assets.xcassets/FinalLocation.imageset/FinalLocation@3x.png
  SeSACTHON_App/SeSACTHON_App/View/MainMapView.swift
  SeSACTHON_App/SeSACTHON_App/View/MainRunView.swift
  SeSACTHON_App/SeSACTHON_App/View/MainRunningView.swift
  SeSACTHON_App/SeSACTHON_App/View/ReportSubmitView.swift
Labels: Design

#194 [Design/#193] PlaceAnnotationView background white
  SeSACTHON_App/SeSACTHON_App.xcodeproj/xcshareddata/xcschemes/SeSACTHON_Watch Watch App.xcscheme
  SeSACTHON_App/SeSACTHON_App/Global/Components/PlaceAnnotationView.swift
  SeSACTHON_App/SeSACTHON_App/View/GlobalProfileImage.swift
Labels: Design

#195 [feat/#185] ProfileView 수정, 연결
  SeSACTHON_App/SeSACTHON_App/Global/Components/TopProfileView.swift
  SeSACTHON_App/SeSACTHON_App/View/HomeView.swift
  SeSACTHON_App/SeSACTHON_App/View/MainMapView.swift
  SeSACTHON_App/SeSACTHON_App/View/MainRunView.swift
  SeSACTHON_App/SeSACTHON_App/View/ProfileView.swift
  SeSACTHON_App/SeSACTHON_App/View/RootView.swift
Labels: feat

#201 Radin del/#196
  SeSACTHON_App/SeSACTHON_App.xcodeproj/project.pbxproj
  SeSACTHON_App/SeSACTHON_App/Global/Components/CustomCameraView.swift
  SeSACTHON_App/SeSACTHON_App/Global/Components/WorkoutBar.swift
  SeSACTHON_App/SeSACTHON_App/Global/Extension/Extra/RunListView.swift
  SeSACTHON_App/SeSACTHON_App/Global/Utilities/RunStateManager.swift
  SeSACTHON_App/SeSACTHON_App/Model/CameraModel.swift
  SeSACTHON_App/SeSACTHON_App/Model/CameraViewModel.swift
  SeSACTHON_App/SeSACTHON_App/Model/WorkoutViewModel.swift
  SeSACTHON_App/SeSACTHON_App/SeSACTHON_AppApp.swift
  SeSACTHON_App/SeSACTHON_App/View/HomeView.swift
  SeSACTHON_App/SeSACTHON_App/View/MainRunView.swift
  SeSACTHON_App/SeSACTHON_App/View/MainRunningView.swift
  SeSACTHON_App/SeSACTHON_App/View/RunEndView.swift
Labels: del

#205 Radin design/#198 러닝 뷰 UI 재배치
  SeSACTHON_App/SeSACTHON_App/Global/Components/RunningRepertSubmitView.swift
  SeSACTHON_App/SeSACTHON_App/Resources/Assets.xcassets/Colors/ListBackgroundColor.colorset/Contents.json
  SeSACTHON_App/SeSACTHON_App/Resources/Assets.xcassets/GORUN.imageset/Contents.json
  SeSACTHON_App/SeSACTHON_App/Resources/Assets.xcassets/GORUN.imageset/Group 55.png
  SeSACTHON_App/SeSACTHON_App/Resources/Assets.xcassets/GORUN.imageset/Group 55@2x.png
  SeSACTHON_App/SeSACTHON_App/Resources/Assets.xcassets/GORUN.imageset/Group 55@3x.png
  SeSACTHON_App/SeSACTHON_App/View/HomeView.swift
  SeSACTHON_App/SeSACTHON_App/View/MainRunView.swift
  SeSACTHON_App/SeSACTHON_App/View/MainRunningView.swift
  SeSACTHON_App/SeSACTHON_App/View/ProfileView.swift
  SeSACTHON_App/SeSACTHON_App/View/ReportSubmitView.swift
Labels: Design

#206 [Feat/#202] Map모드에서 위험요소 이미지 default값 재설정
  SeSACTHON_App/SeSACTHON_App/Global/Components/PlaceAnnotationView.swift
  SeSACTHON_App/SeSACTHON_App/Resources/Assets.xcassets/RunningMan.imageset/Contents.json
  SeSACTHON_App/SeSACTHON_App/Resources/Assets.xcassets/RunningMan.imageset/RunningMan.png
  SeSACTHON_App/SeSACTHON_App/Resources/Assets.xcassets/RunningMan.imageset/RunningMan@2x.png
  SeSACTHON_App/SeSACTHON_App/Resources/Assets.xcassets/RunningMan.imageset/RunningMan@3x.png
  SeSACTHON_App/SeSACTHON_App/View/GlobalProfileImage.swift
  SeSACTHON_App/SeSACTHON_App/View/MainMapView.swift
Labels: feat

#207 [Refactor/#200]
  SeSACTHON_App/SeSACTHON_App.xcodeproj/project.pbxproj
  SeSACTHON_App/SeSACTHON_App/Global/Components/RunningRepertSubmitView.swift
  SeSACTHON_App/SeSACTHON_App/View/MainRunView.swift
  SeSACTHON_App/SeSACTHON_App/View/MainRunningView.swift
  SeSACTHON_App/SeSACTHON_App/View/ReportSubmitView.swift
Labels: Refactor

#208 [Design/#204] 하단 버튼&위험요소아이콘 이미지 에셋 변경
  SeSACTHON_App/SeSACTHON_App.xcodeproj/project.pbxproj
  SeSACTHON_App/SeSACTHON_App/Global/Components/PlaceAnnotationView.swift
  SeSACTHON_App/SeSACTHON_App/Global/Components/RunningRepertSubmitView.swift
  SeSACTHON_App/SeSACTHON_App/Resources/Assets.xcassets/icon_construction_main.imageset/Contents.json
  SeSACTHON_App/SeSACTHON_App/Resources/Assets.xcassets/icon_construction_main.imageset/Group 137.png
  SeSACTHON_App/SeSACTHON_App/Resources/Assets.xcassets/icon_construction_main.imageset/Group 137@2x.png
  SeSACTHON_App/SeSACTHON_App/Resources/Assets.xcassets/icon_construction_main.imageset/Group 137@3x.png
  SeSACTHON_App/SeSACTHON_App/Resources/Assets.xcassets/icon_construction_main.imageset/icon_construction_main.png
  SeSACTHON_App/SeSACTHON_App/Resources/Assets.xcassets/icon_construction_main.imageset/icon_construction_main@2x.png
  SeSACTHON_App/SeSACTHON_App/Resources/Assets.xcassets/icon_construction_main.imageset/icon_construction_main@3x.png
  SeSACTHON_App/SeSACTHON_App/Resources/Assets.xcassets/icon_narrow_main.imageset/Contents.json
  SeSACTHON_App/SeSACTHON_App/Resources/Assets.xcassets/icon_narrow_main.imageset/Group 120.png
  SeSACTHON_App/SeSACTHON_App/Resources/Assets.xcassets/icon_narrow_main.imageset/Group 120@2x.png
  SeSACTHON_App/SeSACTHON_App/Resources/Assets.xcassets/icon_narrow_main.imageset/Group 120@3x.png
  SeSACTHON_App/SeSACTHON_App/Resources/Assets.xcassets/icon_narrow_main.imageset/icon_narrow_main.png
  SeSACTHON_App/SeSACTHON_App/Resources/Assets.xcassets/icon_narrow_main.imageset/icon_narrow_main@2x.png
  SeSACTHON_App/SeSACTHON_App/Resources/Assets.xcassets/icon_narrow_main.imageset/icon_narrow_main@3x.png
  SeSACTHON_App/SeSACTHON_App/Resources/Assets.xcassets/icon_slope_main.imageset/Contents.json
  SeSACTHON_App/SeSACTHON_App/Resources/Assets.xcassets/icon_slope_main.imageset/Group 135.png
  SeSACTHON_App/SeSACTHON_App/Resources/Assets.xcassets/icon_slope_main.imageset/Group 135@2x.png
  SeSACTHON_App/SeSACTHON_App/Resources/Assets.xcassets/icon_slope_main.imageset/Group 135@3x.png
  SeSACTHON_App/SeSACTHON_App/Resources/Assets.xcassets/icon_slope_main.imageset/icon_slope_main.png
  SeSACTHON_App/SeSACTHON_App/Resources/Assets.xcassets/icon_slope_main.imageset/icon_slope_main@2x.png
  SeSACTHON_App/SeSACTHON_App/Resources/Assets.xcassets/icon_slope_main.imageset/icon_slope_main@3x.png
  SeSACTHON_App/SeSACTHON_App/Resources/Assets.xcassets/icon_step_main.imageset/Contents.json
  SeSACTHON_App/SeSACTHON_App/Resources/Assets.xcassets/icon_step_main.imageset/Group 136.png
  SeSACTHON_App/SeSACTHON_App/Resources/Assets.xcassets/icon_step_main.imageset/Group 136@2x.png
  SeSACTHON_App/SeSACTHON_App/Resources/Assets.xcassets/icon_step_main.imageset/Group 136@3x.png
  SeSACTHON_App/SeSACTHON_App/Resources/Assets.xcassets/icon_step_main.imageset/icon_step_main.png
  SeSACTHON_App/SeSACTHON_App/Resources/Assets.xcassets/icon_step_main.imageset/icon_step_main@2x.png
  SeSACTHON_App/SeSACTHON_App/Resources/Assets.xcassets/icon_step_main.imageset/icon_step_main@3x.png
  SeSACTHON_App/SeSACTHON_App/View/MainRunView.swift
  SeSACTHON_App/SeSACTHON_App/View/MainRunningView.swift
  SeSACTHON_App/SeSACTHON_App/View/ReportSubmitView.swift
  SeSACTHON_App/SeSACTHON_Watch Watch App/ReportView.swift
Labels: Design

#209 Radin design/#204 메인뷰 상단바 수정, 러닝 종료시 카메라 버튼 이슈 수정
  SeSACTHON_App/SeSACTHON_App/Model/WorkoutViewModel.swift
  SeSACTHON_App/SeSACTHON_App/Resources/Assets.xcassets/GO.imageset/Contents.json
  SeSACTHON_App/SeSACTHON_App/Resources/Assets.xcassets/GO.imageset/Group 55.png
  SeSACTHON_App/SeSACTHON_App/Resources/Assets.xcassets/GO.imageset/Group 55@2x.png
  SeSACTHON_App/SeSACTHON_App/Resources/Assets.xcassets/GO.imageset/Group 55@3x.png
  SeSACTHON_App/SeSACTHON_App/Resources/Assets.xcassets/GoBtn.imageset/GoBtn.png
  SeSACTHON_App/SeSACTHON_App/Resources/Assets.xcassets/GoBtn.imageset/GoBtn@2x.png
  SeSACTHON_App/SeSACTHON_App/Resources/Assets.xcassets/GoBtn.imageset/GoBtn@3x.png
  SeSACTHON_App/SeSACTHON_App/View/HomeView.swift
  SeSACTHON_App/SeSACTHON_App/View/MainRunView.swift
  SeSACTHON_App/SeSACTHON_App/View/MainRunningView.swift
Labels: Design, Bug

#212 Radin bug/#210
  SeSACTHON_App/SeSACTHON_App.xcodeproj/project.pbxproj
  SeSACTHON_App/SeSACTHON_App/Global/Components/RunningRepertSubmitView.swift
  SeSACTHON_App/SeSACTHON_App/Global/Utilities/RunStateManager.swift
  SeSACTHON_App/SeSACTHON_App/View/MainRunningView.swift
  SeSACTHON_App/SeSACTHON_Watch Watch App/StartView.swift
Labels: Design, Bug

#213 [Design/#165] 위험요소 선택뷰 UI 수정
  SeSACTHON_App/SeSACTHON_App.xcodeproj/project.pbxproj
  SeSACTHON_App/SeSACTHON_App/View/MainRunView.swift
  SeSACTHON_App/SeSACTHON_App/View/MainRunningView.swift
Labels: Design

#215 [Setting/#214] 앱 이름 변경
  SeSACTHON_App/SeSACTHON_App.xcodeproj/project.pbxproj
Labels: Setting

#216 [Feat/#203] 워치 신고 화면 타이머 연동 & 결과 화면 타이머 연동
  SeSACTHON_App/SeSACTHON_Watch Watch App/ReportView.swift
  SeSACTHON_App/SeSACTHON_Watch Watch App/RunningEndView.swift
  SeSACTHON_App/SeSACTHON_Watch Watch App/RunningView.swift
Labels: feat
